---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: alma8
    box: bento/almalinux-8
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.68.68"
provisioner:
  name: ansible
verifier:
  name: ansible
